# Custom Language File for Launcher Customizer

[ejs.app]
title = "En-V Arcade Launcher"

[ejs.landing]
mediaGitHubURL = "https://www.envarcade.com"
mediaTwitterURL = "https://twitter.com/EnVArcade"
mediaInstagramURL = "https://www.tumblr.com/envarcade"
mediaTumblrURL = "https://www.tumblr.com/envarcade"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/xrrQZDAWv5"

[ejs.settings]
sourceGithubLink = "https://github.com/V-Tube-Entertainment/Launcher"
supportLink = "https://github.com/V-Tube-Entertainment/Launcher/issues"

[ejs.welcome]
welcomeHeader = "Welcome to En-V Arcade"
welcomeDescription = "Our mission is to bring the fun to you."
welcomeDescCTA = "You are just a few clicks away from the action."
