# Custom Language File for Launcher Customizer

[ejs.app]
title = "VES Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/V-Tube-Entertainment/Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/V-Tube-Entertainment/Launcher"
supportLink = "https://github.com/V-Tube-Entertainment/Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO V-Tube Entertainment"
welcomeDescription = "Our mission"
welcomeDescCTA = "You are just a few clicks away from fun."
