# Custom Language File for Launcher Customizer

[ejs.app]
title = "VES Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/V-Tube-Entertainment/Launcher"
mediaTwitterURL = "https://twitter.com/EnVArcade"
mediaInstagramURL = "https://www.tumblr.com/envarcade"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/xrrQZDAWv5"

[ejs.settings]
sourceGithubLink = "https://github.com/V-Tube-Entertainment/Launcher"
supportLink = "https://github.com/V-Tube-Entertainment/Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO V-Tube Entertainment"
welcomeDescription = "Our mission is to bring the fun to you."
welcomeDescCTA = "You are just a few clicks away from fun."
